# customer-app-service.yml
apiVersion: v1
kind: Service
metadata:
  name: customer-app-service
  namespace: my-app-namespace
spec:
  selector:
    app: customer-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
