# customer-app-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-app
  namespace: my-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-app
  template:
    metadata:
      labels:
        app: customer-app
    spec:
      containers:
        - name: customer-app
          image: customer-app:0.0.1-SNAPSHOT
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "cloud"
            - name: CUSTOMERINFO_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: customerinfo-config
                  key: CUSTOMERINFO_BASE_URL
